name: Build and Deploy .NET 8 Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Build .NET solution
      run: dotnet build --no-restore --configuration Release
      working-directory: src/Otus.Teaching.PromoCodeFactory.WebHost

    - name: Publish .NET solution
      run: dotnet publish --configuration Release --output ./publish
      working-directory: src/Otus.Teaching.PromoCodeFactory.WebHost

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      run: |
        docker build -t rkirillov/promocode-factory-api:latest -f Dockerfile .
        docker push rkirillov/promocode-factory-api:latest

    - name: Docker Compose up
      run: docker-compose up -d